### ISSUE TITLE
[0.7.7] Time estimates way, way off

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1165]
Time estimates for rastering a square are way, way out.

25mm x 25mm 30mm/s step 4 estimated at 1m22s and actually takes about 4m-5m.

See #847 for suggestion how to do this easily. See also #342.

P.S. Although I am reporting this on 0.7.7, I think fix should only be in 0.8.

**Comment by jpirnay** [comment]
I assume the values are still to be amended, but in 0.8b6 the estimates provided by the ops themselves are exposed now:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/2670784/178964105-fa6272f7-710f-4f1a-8569-955839c47b0e.png">
Maybe this helps for further adjustments

**Comment by tatarize** [comment]
The operations should take different amounts of time for the different backend drivers we may need. The math though is probably due to bad research on the amount of time it takes to do a swing. Since each swing takes a certain amount of time and I think it's mostly doing the math based on the difference, but the turn-around is the bulk of that and something like 0.7 seconds. When you compare that to the time for a single scanline of an inch you'd be going 30mm/s which should take less. In fact we could probably calculate it from the square raster. If we say 4.5minutes and we're doing a 1 inch square at step 4 that's 250 scan lines. If we went at full 30mm/s we'd be doing 250 inches of distance which would be like 211 seconds so 3.51 minutes. And we're losing about 1 minute to turn around time which is probably equivalent to traveling about 71 inches / 250 is about 284 mils of distance added to the end of the scanlines. Though that's a bit predicated on it having given 3.5 minutes there rather than 1m22s.

**Comment by Sophist-UK** [comment]
No - this is NOT the case. I was rastering (NWT) at 30mm/s - each swing was taking 4 seconds. So the turn around time of a fraction of a second was very small by comparison. Yet the estimate was out by a factor of 3x-4x.
