### ISSUE TITLE
[Suggestion]: New Chinese Machines are coming with Right side Homing, Can you Please Upgrade for Right Side Ruler & Homing. 

### ISSUE THREAD

**Issue by Irfan478** [meerk40t/meerk40t#1174]
### Summary Description

Can you Please Generate the Version with RIGHT SIDE Homing. 
Most of the new Chinese machines are coming with RIGHT Side Homing. 
My Machine is on the Right Side HOMING. Im still using MEERk40 but Im facing issues when I look at the Ruler.
In MEERk40 Ruler is on the left side, Because homing is on the Left Side. I'm looking forward to your consideration. 
Regard. 
Engineer Irfan 

### Current functionality

 Machine homing is on the Left Side.

### Future functionality

 homing in  the Right Side. with Ruler starts from the Right Side. 

### MeerK40t Version

0.7

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by Irfan478** [comment]
hmm, THanks for your reply I have downloaded the 0.8 version. will check this out. and I really appreciate your work. Thanks a lot

**Comment by tatarize** [comment]
I'm not sure what is clearly best here. The coordinate system within meerk40t is *still* origin at upper-left (0,0). So when you say to move to (10mm,10mm) it'll convert that into the machine space which should be about 10²mm from the upper-left corner. It converts the scene space to machine space. 

I suppose the correct answer is to set the position in the machine space. I expose the Move-To pane and I give you guide locations  in mock-machine space. When it sends the command though, it does so in scene space which has the real origin in the upper-left there. I neglected to consider the user perceived scene space. Which I guess I could just process in the more outward facing gui commands. It's either correct those or don't swap the guides which would be weirder/wrong.

PS. Try the set position tool, just clicking there is a cooler way to do that.

**Comment by tatarize** [comment]
It should be fairly reasonable. Though testing this we did churn up a few minor bugs.
* The Home Offset is an alternative home rather than an offset.  
* The home-bottom and home-right switches for the M2 Nano do not take effect without a restart of meerk40t.
* Flip-x and flip-y don't refresh the screen it requires a bit of a pan for the numbers to suddenly go negative or whatever.

We're planning on testing some more with some deeper edge cases but I need to get the TCP connection thing a bit more solid and tested, and then there's a couple things like if user_scale_x becomes user_scale_y if you do `swap_xy` and whether that's actually correct or not.  But, in general for most use cases it should be correct. Though it'll still be less stable than 0.7.x for a bit but it's certainly coming together.

**Comment by Irfan478** [comment]
sounds like in future updates. everything is eventually gonna be all okay.
