### ISSUE TITLE
[Bug]:  (continuous jog ) and move, I can't stop moving!

### ISSUE THREAD

**Issue by wenchung01** [meerk40t/meerk40t#1371]
### Summary Description

Hi, I use MeerK40t : RuidaControl (Run my M2 Nano with Lightburn) and I succeeded. 
But I click (continuous jog ) and move, I can't stop moving!
My MeerK40t : console shows  Busy Error again and again! !

![圖片](https://user-images.githubusercontent.com/115357635/194712161-0f55a390-fb90-4be3-a53e-c69b3b13cae8.png)

### MeerK40t Version

v0.7.8

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by tatarize** [comment]
I tested this and it seemed to work. 


https://user-images.githubusercontent.com/3302478/194724013-b059c4b2-a372-451f-9122-2c394da9c3d8.mp4

**Comment by tatarize** [comment]
You could try `alias default` to reset the aliases. Also, you can see them in the console there. They do the same thing as the WASD keys for key down, etc.

**Comment by wenchung01** [comment]
thank you !! I try






在 2022年10月9日 星期日 上午03:23:21 [GMT+8]， ***@***.***> 寫道： 







You could try alias default to reset the aliases. Also, you can see them in the console there. They do the same thing as the WASD keys for key down, etc.

**Comment by wenchung01** [comment]
I can't find the problem, he still doesn't work, and the crash ... >_<"
https://user-images.githubusercontent.com/115357635/195503251-181b0a30-c3c3-4896-9092-c62750b6ca53.mp4

**Comment by wenchung01** [comment]
I can't find the problem, he still doesn't work, I got crash ... >_<"


https://user-images.githubusercontent.com/115357635/195507352-75ac90ea-ac81-4f8c-92b7-743a05719c0c.mp4

**Comment by wenchung01** [comment]
I need to turn off the machine every time, I think....I can't click (continuous jog), only click one-to-one click.

https://user-images.githubusercontent.com/115357635/195509582-bd815ed1-cee7-4295-8488-95164bb6a891.mp4

**Comment by tatarize** [comment]
I seem to recall there was an issue with something like this, where the alias was wrong (I checked this doesn't seem to be wrong). This might be fixed in 0.8.1 since it uses a different methodology to move it.

I believe it can be triggered if it loses a packet to do that. And might be better off using the move position directly in lightburn there. Since that's probably a better way of moving the laser position.

**Comment by tatarize** [comment]
Yeah, this seems to be generally broken in 0.7.x pressing the button fairly easily seems to get stuck. It sometimes recovers but it takes longer than it should. This might be something weird with the timing since it might not be detecting the keypress correctly since it more or less locks up with the positional spamming there.

**Comment by tatarize** [comment]
If you close down the console window it appears to work more consistently. It might be the rate at which it sends data that is largely responsible. It can't process that level of spam in the console window without occupying all of the time for the gui thread which then has no ability to process the key release.

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/commit/a67c273954ccf97605aaba83758209a6302d93b4 should hopefully fix that stuff.
