### ISSUE TITLE
[Suggestion] Hardware speed / bed size limits

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1461]
1. Since we now have speed and power warnings, can we extend that to include speed limits. With these we can extend the speed right-click menu to include more values, and use the limits not only in op properties, but also to limit the speeds shown in the context-menu.

    P.S. Can we increase the number of speed values anyway - my K40 maintains position with normal T2B/B2T rastering u to 525mm/s (but loses it at 550mm/s) so I would like to see 400, 450 and 500 in the menu, and I would personally also like to see more low-speed vector options e.g. 2, 2.5, 3, 3.5, ... 5, 6, 7, ... 10.

2. A more off-the-wall idea is to have speed and bed-size wizards that send a series of specially crafted instructions to the laser to determine speed and bedsize limits with the user hitting STOP as soon as the head loses position. 

    So for bed size, you take a use provided starting-point bed size, and move the head (slowly) backwards and forwards increasingly towards the +ve end stop until the user hears the clunk of the head / rail hitting the ends and tells it to stop. You then Home to regain position and test this across various points in the other dimension, tweaking it back a but if the user hits STOP.
    
    For speed, you do something similar until the head loses position.

    I guess this can be extended to e.g. helping the user to check for positioning accuracy - go to e.g. 1mm,1mm and do a brief dot, move around a bit at speed and go back to the same point and do another dot (which should be in the same place). Ditto for measuring Home variance. You burn a square and get the user to check with a set square. You draw a grid so the user can check for variations in burn amount across the bed. etc.

    Or an alignment wizard that moves the head bac and forth and gives step-by-step instructions on what to do next to get the alignment correct.

    AFAIK there is no other software that has any of this functionality, so it would be a big differentiator.

**Comment by tatarize** [comment]
1. I added in a couple more raster speeds. I also split the cut and engrave to give you more low-end speeds for a vector cut, and the mid and upper end for engrave. I could perhaps see customizing these a bit but if you really need a speed it might be better to make an easier way to enter that.

2. There is in the M2 a weird function that will do back and forth movements without invoking the Y axis. It's weirdly an `S0E` command that invokes there. There's certainly some utility to include some more tests. A regular ramp test for example requires you to draw a line.

There is a home-dot-test. It's hidden but you can type `test_dot_and_home` in console and it should do 25x home dot events. With 50ms firing of the lasers. There used to be a couple jogging tests. But, these all seem pretty rare to use calls. 

The other routine would need constant updates while it's running. That's actually a custom laserjob rather than something like the dot test. It's entirely possible, you'd just send the laser commands to raster in place. Then you'd want to slightly adjust the speed, the right-end, and the left-end (or top and bottom).

There was a long time ago an alignment wizard that was supposed to do that. It would tell you to align the mirrors and gave would do the regular dot test. So hit the button to fire the laser near and far. Now right-and-left. Keep in mind you're aiming towards the points being overlapped not for them to hit the center. It might be possible to get that back or whatever, but it's mostly a gui for somewhat underused tests. I think I got rid of them when I didn't even use it during alignment.
