### ISSUE TITLE
[0.8.1] Scene display of Use rotated element incorrect

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1507]
[Wallet concertina small - Thin 260x150](https://user-images.githubusercontent.com/3001893/203361000-ff0253fc-5d7f-44dd-b0b2-94cc1133c3e5.svg)

When I load the attached file the rightmost piece is displayed 1mm too far left/down. If you look closely the bounds are displayed correctly, but the elements themselves are not in exactly the right place:
![image](https://user-images.githubusercontent.com/3001893/203361552-cc180ee0-f2ed-4f98-907c-39151c8bae9b.png)
This is, however, just a main scene issue. When I  simulate or burn it is correct:
![image](https://user-images.githubusercontent.com/3001893/203361969-04e67d17-8baf-4def-8f57-d6d0681f502f.png)

**Comment by jpirnay** [comment]
Yes, scene is incorrect. Simulation on the other side seems to recognize things properly:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/2670784/203962387-086d6f6c-b3ac-40f5-a0fa-9a22f7594f69.png">
Have you tried to burn this sketch and was it turning out correctly?

**Comment by Sophist-UK** [comment]
On reflection this may not be a Use element issue at all.

**Comment by tatarize** [comment]
It's fine in the preview of the cutcode, and it's also fine when saved out. It has the correct geometry and even gives the correct bounding boxes but clearly shows the path going way too far out around the edge there. I think the issue is that it's actually rounding the control point of the curve. That doesn't really explain why the entire edge is shown wrongly though. But, clearly it seems out of bounds but everything that gives the bounds says it's within bounds. 

![image](https://user-images.githubusercontent.com/3302478/207250121-9fa2dadd-a7d2-4c3a-b137-8ecb593d1d75.png)


It's a bug somewhere in wxPython or meerk40t for the display of the objects. The one wallet face is too low and to the left, the other is too high and to the right. It's weird.

**Comment by tatarize** [comment]
This bug is in a class of bugs including one that is priority: critical. Where values are rounded and then scaled rather than scaled and then rounded. So with a scale of 2800 or so (which is fairly typical) the minimum amount of unit change that matters is 2800. Which is about 4% of an inch. This creates some notable artifacts and we're probably changing the underlying drawing engine for this stuff.
