### ISSUE TITLE
[0.8.5b2] Spooler history estimates are actuals not oiriginal estimates.

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1949]
I had a job with an estimate of 2:11:xx and it completed in 1:02:xx and afterwards the spooler showed the estimate as the same as the actual.

P.S. Estimate was way over due to vertical gaps in the rasters that were skipped.

**Comment by tatarize** [comment]
I seem to recall this happens. It doesn't quite seem like the original estimate that was wrong matters as much when we're done and have the real time.

**Comment by Sophist-UK** [comment]
The way to keep refining the accuracy is to be able to see the inaccuracies.

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/blob/acd0a39a03cd97b9790e5c7667823d17072fe46f/meerk40t/core/laserjob.py#L193

This turns out to be harder than just fixing it. It's not replacing it at the 11th hour. It's actually replacing it based on pass time. So it's using the previous passes to estimate the future passes. So if you have 10 passes and the first two took X amount of time, our new estimate is that the next pass will take 5x the current amount of time. 

This routine gets called when it's done, so its 1/1 for passes and estimates the time it will take to do 1 pass is the time that it took to do 1 pass.

**Comment by tatarize** [comment]
Or not, this looks like if `is_running` were false it should give the purely estimated time. Will fix.

**Comment by tatarize** [comment]
I'll figure it out. #1955 should fix it, when I check the other stuff. Mostly just simplified the logic flow currently.

**Comment by tatarize** [comment]
Fixed.

**Comment by tatarize** [comment]
Also fixed in Legacy8 and should be fixed for the last bug fix release of that.

**Comment by Sophist-UK** [comment]
I cannot believe that you have created a 0.9 version so quick.

I haven't been following 0.9 development, so what are the big changes?

**Comment by tatarize** [comment]
Yeah, fundamentally changing the underlying datastructure sort of required it, even if I manage to get it to work without too much interruption. Though I did limit the scope currently to front-end geometric objects. Cutcode is just planned to be replaced. It might likewise require 0.10.0 in-so-doing.

Well, the point-inside-polygon check can be done in a fraction of the time with numpy. Though the details are a bit cryptic which was actually a lot of time loss in optimization (which is now basically instant). That was done with the underlying path objects so it already got switched out for a pretty marked improvement of speed there. So building the nested tree of closed shapes is pretty fast.

For greedy we could find the nearest element pretty quickly in a command. The complex numbers are used, in part because they are so much like points, and these store the `start`, `control1`, `info`, `control2`, and `end` points. Filter out stuff that is not allowed to be burned yet, and you actually can quickly check the distance from current point to all the start/end points by getting the index of the argument where `np.min(np.abs(segments[:][0,4] - current))` or something like that. Where you can absolutely just have all the segments and you're finding the one with the smallest absolute value of the difference which, if we treat complex numbers as points is actually the euclidean distance.

There is already a built-in two-opt for geomstr, so it's currently trivial to find the shortest TSP path (likely, though not provably shortest). In fact, it might be so fast that we'd opt to use it instead of greedy. I clocked it at 6 seconds for the worst thing I could throw at it back when I first wrote the routine. Though usually the rule is to optimize with greedy then additionally optimize with two-opt.

However, really we can't do traditional TSP since we have a bunch of constraints.  At least when inner-first is checked. If we need all items flagged as 3 to occur before any item flagged as 4 then we can't actually do the regular TSP optimizations because it requires that we flip different paths and take them backwards to see if we improved things. And in the case of the constraints we can't flip those which really hampers the algorithm. 

Though I did read a paper on TSP with constraints which had some interesting suggestions. It was mostly do TSP and when you run into an issue with a constraint remove it. Then when you finish the optimization reinsert it into the valid location minimizes the path. And each TSP path was measured with those steps entirely. Optimize, remove-constrained, re-insert minimal distance constrained nodes.

We also, probably need a couple things like remove duplicated cut lines and a few other things that would throw big wrenches into the algorithms unless it was notably very fast.

**Comment by Sophist-UK** [comment]
Constraints (Inside first, group inside burns) are easy to keep constrained - you can just do two-opt within the constrained set, but that isn't fully optimised. You can also easily resequence the order that the Inside First/Group Inner Burns constrained sets are burned BUT then you will potentially be entering and exiting at the sub-optimal points. I am not sure that it is possible easily to optimise globally for both the sequence of Grouped burns and the burns inside the groups.

However...
     1. Greedy is brilliant at achieving 90% of the savings - without it **either** the head goes all over the place which takes the laser forever, **or** you have to spend time in Inkscape manually sequencing the paths which takes you forever.
     2. My experience with the Raster optimisations in v0.7 that are missing from 0.8 is that when you don't breaking rasters into separate non-overlapping images, the single large raster can cut across several Outer Cuts, spoiling the quality of the Group Inner Burns optimisation. So reimplementing this in v0.8/9 will improve optimisation where you have raster designs inside multiple separate pieces in one burn.
     3. My experience with greedy vector optimisation is that there are two types of burn I do where greedy is significantly sub-optimal. Firstly, for rows of leatherworking stitch holes, when it goes to the nearest hole it sometimes misses one or two at the start of a row of stiches and then needs to do a longish travel to get back to it much later - so if we could find a way to stop these coming much later and insert them somewhere more sensible, that would make a significant difference in the remaining 10% optimisation that is possible. Secondly for Group Inner Burns sometimes it does Group by Group sub-optimally (a macro equivalent of the stitch holes) and then towards the end it to do a long travel to do a later group.

So here is my attempt at explaining my new 2-opt algorithm (and it is difficult to explain, so apologies in advance if I do a crap job at it)...

![tsp](https://github.com/meerk40t/meerk40t/assets/3001893/dd9eb47e-dfe8-458f-8338-52ecb8c88899)

Firstly, whilst some travels (i.e. 0 in this diagram or the ones along the bottom and left side to return to origin) will be long simply because the burns are a long way apart, as greedy gets a smaller and smaller choice of remaining burn segments, so the probability of a longer travel to mop up burn segments that would ideally have been done earlier increases (i.e. 3).

So the idea of this algorithm is to identify a group of burns with relatively long travels before and after and a relatively near earlier burn, and then find a group of burns (with travels either side) that can be moved as a group to an earlier point in the burn, somewhere near the burn immediately following a long travel.

So the idea is to consider only long travels (> than some threshold - perhaps an absolute distance of (say) 1" or perhaps relative to the the largest hull dimension of the group being considered) and then try to find two long travels (3 and 4) where if you cut out the burns between 3 and 4 and reinsert them one side or another of the nearest (earlier) burn (so the group between 1 and 2 in the diagram) such that the lengths of new travels A + B + C is less than the lengths of the travels they replace 1 + 3 + 4.

The concept of the algorithm is as follows:

* Make a list of long travels and iterate backwards through the list (because greedy means that the longer optimisable travels will be later in the job) ignoring the return to origin travel. For each of the long travels (e.g. 3)...
* First you take the immediately following burn segment (after 3) and find the nearest earlier burn segment (before 3). This is your initial version of B (though this will get modified later) of a known length.
* Now we want to iterate forwards to try to find a group of burns and travels such that the extra travels B*2 + C is less than 3+4. (If we have this, then we know that travel A <= travels 1 + B and so A+B <= 1 + B*2, so A+B+C < 1 + 3 + 4.)
* If we have such a group, of burns and travels, then we now need to find the travels either side of the nearest earlier burn segment and then decide which side of the nearest earlier burn segment we should move the group to. i.e. see whether A+B (replacing 1) - 1 is < or > A'+B' (replacing 2) - 2. When deciding this we can also reverse the group we are planning to move if that helps decrease the travel distance, but the rest is left alone.
* Then if we move this group of burns as shown, we will have reduced the travel distance/time without changing the burn time.

There will be various complications to ensure that constraints are maintained if outer cuts are included in the group or if the nearest earlier burn segment is part of a Group Inner Burns group (2-Opt travel optimisation is aborted or the definition of 1 and 2 is adjusted so that the earlier burn segment expansion is increased to the full Group Inner Burn group). This will need careful thought, but should be possible to code reasonably easily.

As you can see, for each of a relatively small number of long travels the iterations here are of O(N) rather than O(N^2), and the number of iterations is going to be substantially curtailed beyond that. So the performance of this algorithm should be good.

That said, this feels like a linked-list manipulation algorithm having a sequenced list of burns/travels and cutting a sub-chain from this linked list from one point in the list (possibly reversing them) and inserting them at an earlier point in the list. This doesn't feel like a numpy solution, and a numpy brute force 2-opt might still be quicker than this non-numpy algorithm.

**Comment by tatarize** [comment]
I had previously missed this comment. I made a bunch of things flag any comment seen on github a bit more obviously.

1. While I think that optimizing subsections between constrained sections is probably leaving a lot on the table it would probably be the way to go and for most practical applications would be good enough. In theory you could optimize a number of don't care elements both between and to either sides of constrained objects and the constraints simply must be kept in the right order. The other objects can flow to optimize. 
        b. the algorithm there is a bit extreme and typically means doing two-opt removing any objects that is constrained in illegal ways, remove the illegal objects. Then reinsert them in the constrainted version and use that entire system (with the removal and reinsertion in a greedy fashion) as the distance calculation of that two-opt operation. 

2. This division of objects into non-overlapping sections in order to be non-spaghetti needs to basically work outside of cut planning complete. We should be able to call a function and divide an image into reasonably contiguous regions that are good for optimizations. Which could be seen as a kmeans clustering-like problem where you decide which pixels are non-white and simply try to cluster them.

3. Two-opt within permitted sections would fix the two missing hole problem three. Since two-opt would never be fooled as to the optimal path. It's a bit slower, but with geomstr (which is currently only used on the front end and not the backend during cut planning (but is planned to be used there)) this could be made fast enough that users don't notice. 

---

The given algorithm seems like it's going to at best be like two-opt without being like two-opt. You're performing optimizations but you're specifically just focusing on the longer paths to perform what is, in essense, two-opt. Can a two-opt improve these long sections. Though really the question is whether the two-opt can improve anything and maybe give up when some criteria is met. 

In practice linked lists always suck. It's just a weird fact of code, they never out perform lists even for jobs they are ideal for. Here, depending on the ordering replacing we have to, for example, reverse the direction of a long list of cuts. And while that operation is doable it means visiting each of them and reversing the head and tail sort of thing.

Two-opt generally states that we have a path, and this path has a jump-distance value. Then the question two-opt answers is that if we go through this path and we flip (both the segments themselves and the subpaths of segments) something inside can we make this path shorter?

Our geomstr paths are basically:
```
a[S1I2E]b
c[S1I2E]d
e[S1I2E]f
g[S1I2E]h
i[S1I2E]j
```

Flipping 2nd - 3rd segments:

```
a[S1I2E]b
f[E2I1S]e
c[E2I1S]d
g[S1I2E]h
i[S1I2E]j
```

Blocks of data with start, control 1, info, control 2 and end. can we grab any chunk of these segments pull those blocks out and rotate it 180 degrees (still leaving a valid path) and reduce the overall distance? We can test this by just seeing if `b->c + f->g` is smaller than `b->f + d->g` and if it is shorter we keep that.

In numpy we can do this by flipping the actual bits in memory very easily. You're idea feels to be about the same but trying to just do the worst offenders earlier. But usually we're talking about fractions of a second and can just try everything, and then try them all again, and keep trying them until there's no improvement.
