### ISSUE TITLE
Add in Pre-Job Warnings.

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#213]
* Warning some of your design is outside the know bed position.
* Warning your speed is set to more than 100mm/s for a vector. That's really high.

Might be added as part of project foresight.

**Comment by Sophist-UK** [comment]
Although I had allowed 5mm each side between a very wide raster and the end-stops, it turned out that at the very fast raster speed (450mm/s) this was not enough and it hit the end stops and shifted (a lot) ruining an entire piece of material.

So a warning that - with acceleration distance - a raster is outside the bed dimensions would be VERY useful.

**Comment by jpirnay** [comment]
https://github.com/meerk40t/meerk40t/pull/2401
