### ISSUE TITLE
[Suggestion] Burn inside first algorithm - images

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2192]
I have a feeling that the "burn inside first" algorithm handles images differently from paths.

IIRC, the paths are interpolated for a certain number of points, and then non-cut paths are checked to see if any of their points are inside the cut path. This is optimised by checking whether the bounding boxes overlap first and only checking path points if there is some overlap of bounding boxes.

I have a feeling that potentially inside images only do the bounding box test and not the path inside test.

If this is the case, then my suggestion is that images also do the path inside test using the image bounding box, the benefit being when the image bounding box does **not**  intersect the cut path but does intersect the cut path bounding box.

**Comment by tatarize** [comment]
Yeah, if the images are regarded at all they are treated like a rectangle for the purpose of burn-inside first. 

They would more properly be treated differently not just to do things like subdivide them into contiguous parts but also, yes. If we burn inside first. And we have an `image` with a circle cut out, that is fully inside that image. The goal of the project is clear. Raster everything there, then cut this one piece of the image out. -- That goal would actually be negatively inclined by `burn inner first` since it would require that it wrongly put the cut down first before the raster even if you tried to expressly put it the other way.

**Comment by Sophist-UK** [comment]
Clearly I have failed to explain myself here.

There is a difference between treating the image as a rectangle and comparing bounding boxes with a cut path and treating the image as a rectangle and checking whether it is inside, outside or crossing a path using the (something or other) algorithm.

I suspect that images are currently checked **only** using bounding boxes, and I am suggesting that they should be treated as a rectangular path and checked using the same full algorithm as any other path.

**Comment by Sophist-UK** [comment]
![image](https://github.com/meerk40t/meerk40t/assets/3001893/e3a3a2bf-4c63-420a-942c-d27ef161f63d)

In this example, using only bounded boxes the image is partly inside the circle. But using the bounding box for the image as a path and comparing it with the path for the circle, the image is entirely outside the circle.

**Comment by jpirnay** [comment]
I may not understand the issue here, but isn't the inside check discarding candidates by checking whether the boundaries are slightly outside of the inner area? Admittedly it checks the outer hull of real paths, but in essence it is the same: if you are partially outside the bbox you are outside of the hull too. Not necessarily the other way around though, so if outside the hull you may still be inside the bbox.
I wasn't able to create an example where it would make a difference, so a real world specimen would be welcome together with an explanation what you would have expected, please ? Thank you.
(the code where it is checked would not be that difficult to change, actually I did it, but I couldn't see a difference as outlined above).

**Comment by Sophist-UK** [comment]
I raised this because I noticed that the outer path was not burned when an image corner overlapped the bbox but didn't overlap the cut path - in other words a real-world example. 

The graphic example (which I took time to draw) is a simplified version of this real-life event, and shows an example where if there were paths inside the circle they would be burned, but the cut would not be burned as it should be until the image had been burned too.

**Comment by Sophist-UK** [comment]
I don't think this has been completed either.

There is an algorithm that the Burn Inside First uses to check whether a path is entirely inside or outside of another path (I can't remember the name off-hand) but images do NOT use this algorithm and instead use a simplified bounding box corner algorithm. All I am suggesting here is that images are compared to cut vectors by treating an image as if it is a rectangle and use the standard algorithm. This would IME be a very small change of code (because we have the algorithm already).

**Comment by jpirnay** [comment]
Can be picked up - optimisation changes / fixes will go the backlog for now, as the full comprehension of the underlying routines needs to be established first.

**Comment by jpirnay** [comment]
I fail to see the use case for this:
images are treated within an image operation, they are always dealt with as their own cutgroup afaics - so the sequence of operations in the tree does matter, if they come before a cut/engrave then will be burnt before a cut/engrave.
![grafik](https://github.com/user-attachments/assets/2217b68f-2382-40e4-b23b-58af3b5ee622)

If no testcase can be provided then I will close this again.

**Comment by Sophist-UK** [comment]
The use case for burn as a group is to reduce the amount of spoilage if something goes wrong - you burn each component of a multi-component sheet before you move onto the next one. This prevents that happening.

That said the actual optimisation benefit in terms of reduced travels is low, and the times you get a burn fail are low, so if this wasn't IMO likely to be an easy fix I would drop it.

But I expect it is likely to be a 2-5 line fix for the reasons previously given.

**Comment by Sophist-UK** [comment]
I just checked the code. Handling rasters is done differently at https://github.com/meerk40t/meerk40t/blob/c48ada18da673d9c8c3769ac4795338572f04279/meerk40t/core/cutplan.py#L871C1-L878C1 - I think if you delete these lines and instead make a slightly different call at https://github.com/meerk40t/meerk40t/blob/c48ada18da673d9c8c3769ac4795338572f04279/meerk40t/core/cutplan.py#L939 if the inner object is a raster where you replace the inner path with a rectangular closed path of the 4 corners.

**Comment by jpirnay** [comment]
Thank you for the input, I would still need an example, please, to check whether the more elaborate logic I did include in my code works. I can't be able to trigger the inner_first_ident routine.
