### ISSUE TITLE
[0.9.4b1] Simulation/burn estimates - what exactly is extra time and why is it humungous

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#2327]
19mins burn time (realistic), 11secs travel time (about right), 17.5mins "extra time" for "turnaround" (WTF????!!!!).

![image](https://github.com/meerk40t/meerk40t/assets/3001893/70cd45c1-aefe-4a8c-a66f-41eb9d4a00a9)

So what exactly is extra time and how is it calculated?

**Comment by Sophist-UK** [comment]
In this example, no waits - Origin, burn, Origin - nothing to account for c. 80% "extra time" being added to burn time.

**Comment by tatarize** [comment]
The turn around in the raster is counted in extra time. If I otherwise count just the time it takes to go at speed it would finish significantly faster. This time is added on and calculated and timed for the decel-accel cycles. If the actual resulting time is wrong and much closer to 21 than it is to 38 then feel free to complain. But, it is the case that a bit less than about half the time spent lasering is spent turning around.
