### ISSUE TITLE
[Bug]:  Material Library "Load into Tree" ignores Manual Classification setting

### ISSUE THREAD

**Issue by kostex** [meerk40t/meerk40t#2431]
### Summary Description

With manual classification setting enabled selecting a material (with multiple operations) from the library and clicking "Load into Tree" it still classifies (all) objects.
As a side note.. with classification on, for example, if there are several raster operations in a material, all scene objects will be put in all raster operations. For me, this is the reason to disable auto classification altogether. I think it would be more useful to only (auto)classify the current selected object(s)

Thank you for looking into it,
Cheers!

### MeerK40t Version

Latest commit

### MeerK40t Type

Git

### Your Operating System

Linux

**Comment by jpirnay** [comment]
The automatic classification has been resolved.

On your remark re classification, please give this a read:
https://github.com/meerk40t/meerk40t/wiki/Online-Help:-CLASSIFICATION
In essence, the behaviour you describe is intentional, operations are greedy to adopt elements, you need to constrain them:
- check the color for fill to restrict the assignment to fitting elements
- check the stop mark if you want to prevent adoption by other operations
- Additionally the order of operations is relevant, so if you have done the above but other raster operations are above this one then they might have already doen their bit and adopted it.

So if you need to have multiple raster operations, then look at the order and check the adoption flags.

(Having said all that, we will still check the logic that there aren't exceptions / flaws which are unintended)
