### ISSUE TITLE
Resample Issue - RasterWizard, Resample and DitherType Disabled

### ISSUE THREAD

**Issue by tomislav17** [meerk40t/meerk40t#246]
why can't I set the exact size? I can only set the size with the mouse
![12](https://user-images.githubusercontent.com/61805701/96395278-85bdc200-11c4-11eb-80ec-ee8fad80351e.jpg)

dithering doesn't work either
![13](https://user-images.githubusercontent.com/61805701/96395500-12688000-11c5-11eb-9c36-c636887283e6.jpg)

**Comment by tatarize** [comment]
You could do this in Position. Where it lets you edit the selected items size that way if you need an exact size. I was going to allow this but wanted the version out since RasterWizard was pretty awesome and I wanted people to have it, so I ended up turning off anything that wasn't going to be added this go round. There are several different dithering algorithms but Floyd-Steinberg was the only one already in Pillow so, I would have needed to do a manual process of all the pixels to do the other ones, and it would make it really sluggish, and it was a lot of work, so I turned that off too.
