### ISSUE TITLE
When Engraving, a STOP button needs to Stay ON-TOP

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#295]
I found out the hard way that the STOP/Pause button is -NOT- where I thought it was...

When something is "Spooling" (or not, haven't tried it without the spooler) 

 there needs to be an OBVIOUS, EASY TO REACH     --**STOP**-- button.

The current "Stop/Pause" is not under a regularly opened window, so when something is going wrong, it is NOT the time to go looking for the STOP button

**Comment by tatarize** [comment]
I added https://github.com/meerk40t/meerk40t/pull/282/commits/9dd645e4d2cf10904875e8cc6c5cb0a89686717f Big Floating Red Stop Button. I might be halting use of AUI before 0.7.0 because I'm not really going all-in there, so it's weird you can't drag things over from navigation etc. And I might need some better understanding and background on that. Since I tried to rewrite some of CameraInterface with it in 0.7.0 and ended up so broken, I started my correction over again. I got multiple camwin stuff working in 0.7.0.
