### ISSUE TITLE
Multiple Meerk40T's running??

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#369]
I was having some weirdness, so I thought I would close and re-boot.

When I closed MeerK40T, there was ANOTHER session still present that I thought I had closed

I had -4- copies of MeerK40T running.  Well, not running, but loaded.

I Would SUGGEST unless people are running a beast of a computer, and/or multiple K40's, that you do a test to see if another instance of MeerK40T is running and give a warning if it is.  OR, like many other programs, have a box that specifically allows/deny's multiple instances of the program.

As an additional note, when I went to upgrade the computer connected to the K40 from 6.16 to 6.19 I got a message saying that MeerK40T was LOCKED even though I had closed it.  Wouldn't let me delete the old version until I had rebooted to unlock the file. I had exited cleanly, wasn't a crash, so the EXIT routine isn't closing everything all the time.

**Comment by tatarize** [comment]
Sometimes it's possible to have a thread that lives beyond the close. This usually implies something was sending or for some other reason it refused to die. This is not very typical but, they are light threads when they do that.

Your suggested solution there is clearly a worse problem since there are reasons to explicitly allow this. In 0.7.0 there's a -P profiles tag to run the settings so they don't step on each other so you can run multiple copies of MeerK40t at the same time without any issue. Really what needs to be done is find why the meerk40t didn't correctly die and correct those errors.
