### ISSUE TITLE
Question about terminology or units and standardization?

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#379]
Trying to standardize my material testing.

Since Three (3) factors affect all stages, but cutting is easiest to understand....

If to CUT through a material it can be done at:

20mm/sec  at 800ppi and  6ma

If PPI is really something/ second

I end up with (20mm/0.8 PPI ) X 6ma   or .3ma/mm

So I can change anything I want, power, power factor, or speed, and as long as the result is .3ma/mm the result will be the same.

for example, I know that really intricate detailed objects cut better slower, so to get the same results at 15mm/sec I would only need 750ppi if I leave the power the same.  Or at 10mm/sec only .5ppi (500 or 50%)

(Is the result ma./mm or ma.-seconds/mm)

Is my thinking correct... I know the results work

**Comment by tatarize** [comment]
Somewhat close to that. There's some caveats. You could put your PPI to 500 and dot length (in 0.7.0) to 50 and you'd likely never cut anything because you'd be cutting lines of 50 mils and likely would make something you could punch out but not a clear cut. Though that's a bit of an extreme example.

The math is a little off than what you get in that. Speed is negative correlated whereas PPI is positive correlated. And ma is likely also positively correlated, but kind of variable.

In the end if you did all the math the stuff that matters is photons per unit area. This actually is the ultimate measure. And we can see that all of our factors will actually directly relate to this.

If we go twice as fast and the flow of photons from our laser remains the same, we get half as many photons over the same area.

If we add in a PPI of 500 from 1000. We now flicker our laser on and off each step and the so we have it on half as often, which means we half the "photons per unit area".

If we do a ramp test and focus our laser better. We have the same number of photons as we did before. But we've reduced the focus spot from larger to smaller. Which increases our photons per unit area. (by decreasing area)

If we increase our raster-step from 2 to 3. We will decrease the scanlines we use. So if we were 1000 mils high for our raster that would have been 500 scanlines but now it's 333 scanlines (at the same width). Photons per unit area is 2/3 the previous value.

If we crank up the power. We non-linearly increase the photon rate of our laser (sometimes, sometimes added power causes fewer photons and damage). Which directly relates to our photons per unit area.

---

For math purposes you can see the relationships such that if everything is held the same the two clearly linear values will be speed and ppi. You can do `ppi/(mm/s)`. If you want to bring the knob into it you might have to measure the actual cut power with ppi and mm/s held constant, adjusting only the knob.  Until you know what mm/s corresponds to a linear cut amount.
