### ISSUE TITLE
Ratio for xy not in rotary mode ?

### ISSUE THREAD

**Issue by jhindes521** [meerk40t/meerk40t#427]
Would it be possible to implement the custom ratio of x and y like in the rotary mode but for normal engraving / cutting for dimensionally accurate parts. 

This works with the rotary but it disables the auto home after completion  

Regards 
J

**Comment by tatarize** [comment]
As a temporary work around you can add auto-origin (Return to Origin) after completion. This doesn't trigger the device's home function but rather sends the device to (0,0) or where meerK40t presumes 0,0 should be. 

In addition to the nerfed home, there's other reasons this slight difference matters usually with regard to the visualizations. The screen says what 1mm is but if your x steps are 0.93 mils rather than the 1:1 assumed, it's going to be an issue.

Also, you could scale the vectors manually, without rotary. In 0.6.x if you hit F9 it'll let you perform a transformation on the selected objects: `scale(0.93,1)` would for example reduce the x width by 7%

---

Also see #281

**Comment by tatarize** [comment]
This should be mostly settled with the coordinate system in 0.8.x
