### ISSUE TITLE
Mouse over hints on some buttons would really help

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#53]
Quite a lot of buttons would benefit from a mouse over text.
Might help people find out features for themselves and lessen the amount of questions you get.

**Comment by dietervansteenwegen** [comment]
Although, I must say I like your buttons icons...

**Comment by tatarize** [comment]
They are Icon8 icons. They have some nice ones and fit with the same theme once you pick them.  I haven't actually deleted the icons directory, since I might still use some but for a number of technical reasons icons are best distributed in python with converting them to text. Hence the icons.py file. It properly bundles like the rest of the file but things like pyinstaller get much easier when you don't need to include actual files other than python.

But, it does remind me that, I should make an about dialog.

"DESKTOP APPS
macOS and Windows applications should have the link to https://icons8.com in the About dialog."

Oh, and probably more mouseover hits for buttons. And other elements. :)

**Comment by tatarize** [comment]
- [ ] Alignment
- [ ] BufferView
- [ ] ColorDefine
- [ ] Controller
- [ ] ElementProperty
- [ ] JobInfo
- [ ] JobSpooler
- [ ] Keymap
- [ ] Navigation
- [ ] Preferences
- [ ] Usbconnect

**Comment by tatarize** [comment]
The unhinted windows have been marked.
