### ISSUE TITLE
Laser trace does not update/redraw when zooming

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#58]
Not sure if this is worth looking into.
When a job is done, if you zoom in to the path that the laser followed you get something like this:
![2019-09-27 20_10_35-MeerK40t](https://user-images.githubusercontent.com/46349482/65791984-1dd4ad80-e163-11e9-822a-54734f272724.png)
Or maybe that is really the path because the imported SVG gets scaled to about 1/20th of the real size.

**Comment by tatarize** [comment]
Yeah, the trace lines there are anywhere you laser head was. It's actually a bit of a bad design. Basically it tracks the last 500 locations (maybe 50) of the laser head and just draws those lines between them. They stay there because those lines still exist. I could trash them altogether or change them to mean something else or figure out a better way of doing that altogether. Basically I have an updated location for the laser head, and wanted something to indicate where it was.

**Comment by tatarize** [comment]
This problem has gotten worse as the trace lines are signaled and as such don't even connect anymore. Running a project just leaves some pointless crap in the scene.

**Comment by tatarize** [comment]
This is somewhat fixed. It now deletes when you click on a different item to be selected. Also, 178 can be the main objection here.
