### ISSUE TITLE
Can’t open on Mac

### ISSUE THREAD

**Issue by knutaugust** [meerk40t/meerk40t#638]
Hi, I’m very interested in testing this software as it looks promising, but unfortunately I’m not able to open it on my Mac. The application crashes immediately. Im running MacOS Big Sur 11.6. Any suggestions?

**Comment by apbarratt** [comment]
Hi guys,

Sorry for delay in reply.  The file named MeerK40t.dmg does not run on my Mid 2011 MacBook Air.  The crash log is as follows:

`Process:               MeerK40t [6990]
Path:                  /Applications/MeerK40t.app/Contents/MacOS/MeerK40t
Identifier:            org.tatarize.MeerK40t
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MeerK40t [6990]
User ID:               502

Date/Time:             2021-10-29 19:40:35.009 +0100
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        270FF13F-214F-6037-FFF9-25D9C98DE408

Sleep/Wake UUID:       A25D99AE-A186-4E31-A450-32281B0843A3

Time Awake Since Boot: 53000 seconds
Time Since Wake:       36000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010423a000-0000000104244000 [   40K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x000000010732119c _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeeb9c5be0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010732119c  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10423a000 -        0x104243fff +??? (0) <6F7D2EAA-668F-34F8-96E5-C42A61B62A37> (null)
       0x107320000 -        0x10736aadf +??? (551.5) <CB9BFB56-4511-36F1-A546-891FF770C01C> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 23782
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=5304K resident=0K(0%) swapped_out_or_unallocated=5304K(100%)
Writable regions: Total=8428K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8428K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                             252K        5 
__LINKEDIT                        4964K        3 
__TEXT                             340K        3 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             69.4M       12 

`

The file named MeerK40t_PyInst_11.dmg does in fact install a version that opens and looks amazing.  However it complains that no Backend LibUSB driver exists.  I have attached a screenshot.  I'm afraid no further information is logged to the terminal when I run using it.

I did open a second issue for this as I feel this one is a very different bug, but for some reason it was closed as a duplicate to this one :/ 

![Screen Shot 2021-10-29 at 19 43 18](https://user-images.githubusercontent.com/642320/139486340-f2bad7a7-3424-45cc-9609-aefd3ab86bab.png)

**Comment by apbarratt** [comment]
My version of Mac OS is 10.13.6, which is the furthest this Mac will upgrade.

I am soon planning to experiment with running on my M1 Mac and running the machines remotely from meerk40t using a Pi :)

**Comment by tatarize** [comment]
You don't even need the pyusb thing to work if you run over TCP. Just run it on the pi and save yourself the long usb wire and send data to the laser as such. We might need better instructions for setting this up on the pi, they did some stuff making it so the pi-0w would autoboot into a useful mode.

And unless the protocol changes you rarely need to update the pi even when you update meerk40t. So things like when I added in a % command to mean get this packet's checksum wrong (a user had a usb sniffer thing and was using it to trigger other devices and sending a packet to be ignored by the machine would allow you 30 bytes of commands that did nothing for the board but did *anything* for the zbed, usb lights, etc) or if I go through and update the Ruida emulation stuff (you can run a `ruidacontrol` on the same thing running the `lhyserver` and go ahead and *also* control the laser with lightburn if you wanted (it might be of some limited utility)).

**Comment by joerlane** [comment]
@apbarratt  For the time being I've uploaded a MeerK40t_unsigned.dmg. 

It looks like I need to sign the app differently for older versions of Mac OS X. That should fix the issue with crashing because of codesigning on OS X 10.13, but I'll need to setup an older machine to do that for me.

While I know libUSB is inside the pyinstaller auto-generated build; it appears not to be compatible with the older Mac OS X version. I think I can swap that out in the future with a more compatible version. 

Let me know how the unsigned MeerK40t works out for you; I don't see any reason it shouldn't work.

**Comment by joerlane** [comment]
0.7.4-beta1 is released with a compatibility version of libUSB in the Autobuild. 

The Meerk40t.dmg and unsigned versions are also built for compatibility, and I've tested both signed and unsigned in Mac OS X version 10.12.

**Comment by joerlane** [comment]
Legacy (py2app built) type M1 build was added for MeerK40t versions 0.7.3. MeerK40t_M1.dmg That should work fine anywhere previous MeerK40t M1 builds did.

Still working on the conversion to pyinstaller for the M1 which plays well with the Mac App Store.
