### ISSUE TITLE
[Minor improvement] Rapid move as Device Config

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#654]
Rather than have Rapid Moves as an Execute option, can we move it to Device Config to work the same as Pulse Grouping i.e. you can turn it on/off dynamically?

**Comment by tatarize** [comment]
Turning it off dynamically might not be safe. I'd have to check. But, I'd guess it's either in a jog or it's not in a jog so it seems like it would work.

And it should certainly be in properly Device Config of the actual device since many other lasers won't let you actually toggle that. If you move the laser while it's off it goes at rapid speed. There's no fine grain control for that, and little reason you'd want to do that.
