### ISSUE TITLE
Stroke-width is not accounted for in make-raster size of images

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#667]
https://www.facebook.com/groups/716000085655097/permalink/952890345299402/

Seems to arise in the wild where people would like to raster their shapes correctly.

**Comment by Sophist-UK** [comment]
I will get around to fixing this when I get the time - it is not difficult, esp. since I added the functionality to SVGelements to include the stroke width in the bbox.

This needs to be done for:
a. Burn prep (simulation and actual burn)
b. Right click and convert raster elements to image
c. Console command to create raster image.

There should also be a consistent way of determining the bbox of selected elements (from memory several ways are used in different places).

Because it is in the same code, I was also saving this up for doing with optimisation of raster elements to break raster elements into multiple images if they include large amounts of whitespace and would be quicker done in several smaller images.

**Comment by tatarize** [comment]
The make_raster command in line 504 in planner and 3068 in elements is being fed the bounds to make the rasters at. Usually by some Group.union thing.

You made group union accept with_stroke=False.

**Comment by Sophist-UK** [comment]
It was about 10 minutes to code and test - including fixing the classify_reverse issue.

**Comment by tatarize** [comment]
Approved. Though mixing and matching different checks took a bit longer. But, yeah, that stuff would feed in there and I'll assume you tested that since it tends to matter only with obfuscation objects.
